print("CONTACT FORM\n")
name = input("name - ")
age = input("age - ")
course = input("course - ")
contact = input("conatct number - ")
print("")
print("the name you entered is",name)
print("the age you entered is", age)
print("the course you entered is",course)
print("the contact number you entered is", contact)
confirmation = input("the information you have provided is true, please confirm by typing 'yes' - ")